# Generated by Django 3.1.14 on 2025-04-14 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_accordion', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_attribute', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_bannerslider', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='IconRow',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_iconrow', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_integration', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Integration', max_length=255)),
                ('subtitle', models.CharField(default='We collaborate with Top E-Commerce CMS in the World', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='StepContainer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_stepcontainer', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(max_length=2550)),
                ('shown', models.BooleanField(default=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bulqsoftDjango.stepcontainer')),
            ],
        ),
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image_height', models.IntegerField(default=1000)),
                ('image_width', models.IntegerField(default=720)),
                ('shown', models.BooleanField(default=True)),
                ('link', models.CharField(default='#', max_length=2550)),
                ('Integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='bulqsoftDjango.integration')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_images', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.FileField(upload_to='icons/')),
                ('width', models.IntegerField(default=80)),
                ('height', models.IntegerField(default=11)),
                ('is_padded', models.BooleanField(default=True)),
                ('shown', models.BooleanField(default=True)),
                ('icon_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='bulqsoftDjango.iconrow')),
            ],
        ),
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=100)),
                ('shown', models.BooleanField(default=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to=settings.FILER_IMAGE_MODEL)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='bulqsoftDjango.bannerslider')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.CharField(default='', max_length=255)),
                ('icon_class', models.CharField(default='lqd-icn-ess icon-lqd-mobile', max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributeitems', to='bulqsoftDjango.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.CharField(default='', max_length=255)),
                ('shown', models.BooleanField(default=True)),
                ('accordion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordionitems', to='bulqsoftDjango.accordion')),
            ],
        ),
    ]
