# Generated by Django 3.1.14 on 2025-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulqsoftDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconrow',
            name='height',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='iconrow',
            name='is_padded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iconrow',
            name='width',
            field=models.IntegerField(default=80),
        ),
    ]
