# Generated by Django 3.1.14 on 2025-04-14 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('bulqsoftDjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordion',
            name='highlighted_title',
            field=models.CharField(default='Ecosystem', max_length=255),
        ),
        migrations.AddField(
            model_name='accordion',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accordion_images', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='accordion',
            name='image_height',
            field=models.IntegerField(default=979),
        ),
        migrations.AddField(
            model_name='accordion',
            name='image_label',
            field=models.CharField(default="Lets's chat", max_length=20),
        ),
        migrations.AddField(
            model_name='accordion',
            name='image_width',
            field=models.IntegerField(default=1283),
        ),
        migrations.AddField(
            model_name='accordion',
            name='label',
            field=models.CharField(default='ONE PLATFORM UNITES ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='accordion',
            name='title',
            field=models.CharField(default='Join Game Changing Store Management', max_length=255),
        ),
        migrations.AddField(
            model_name='accordion',
            name='title_post_highlight',
            field=models.CharField(default='by Bulqsoft', max_length=255),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='body',
            field=models.CharField(default='The Most Important Attributes That Differentiates Us From Others.', max_length=255),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title',
            field=models.CharField(default="Pioneering Tomorrow's Software Today", max_length=50),
        ),
        migrations.CreateModel(
            name='BananaBanner',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_bananabanner', serialize=False, to='cms.cmsplugin')),
                ('back_text', models.CharField(max_length=255)),
                ('front_text', models.CharField(max_length=255)),
                ('front_text2', models.CharField(max_length=255)),
                ('image_height', models.IntegerField(default=1123)),
                ('image_width', models.IntegerField(default=2080)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banana_images', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
