# Generated by Django 3.1.14 on 2025-04-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulqsoftDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_attributeitem', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='', max_length=30)),
                ('body', models.CharField(default='', max_length=255)),
                ('icon_class', models.CharField(default='lqd-icn-ess icon-lqd-mobile', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
