# Generated by Django 3.1.14 on 2025-04-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulqsoftDjango', '0003_attributeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeitem',
            name='icon_class',
            field=models.CharField(default='lqd-icn-ess icon-lqd-mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='attributeitem',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
