# Generated by Django 3.1.14 on 2025-04-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('bulqsoftDjango', '0004_auto_20250411_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_accordionitem', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
