# Generated by Django 3.1.14 on 2025-04-13 19:07

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('bulqsoftDjango', '0006_bannerslide_bannerslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslide',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
