# Generated by Django 3.1.14 on 2025-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulqsoftDjango', '0007_auto_20250413_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslide',
            name='shown',
            field=models.BooleanField(default=True),
        ),
    ]
