# Generated by Django 3.1.14 on 2025-04-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('bulqsoftDjango', '0008_bannerslide_shown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.FileField(upload_to='icons/')),
                ('width', models.IntegerField(default=80)),
                ('height', models.IntegerField(default=11)),
                ('is_padded', models.BooleanField(default=True)),
                ('shown', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IconRow',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_iconrow', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
