# Generated by Django 3.1.14 on 2025-04-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulqsoftDjango', '0009_icon_iconrow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
