# Generated by Django 3.1.14 on 2025-04-13 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulqsoftDjango', '0010_delete_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.FileField(upload_to='icons/')),
                ('width', models.IntegerField(default=80)),
                ('height', models.IntegerField(default=11)),
                ('is_padded', models.BooleanField(default=True)),
                ('shown', models.BooleanField(default=True)),
                ('icon_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='bulqsoftDjango.iconrow')),
            ],
        ),
    ]
