# Generated by Django 3.1.14 on 2025-04-13 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('bulqsoftDjango', '0011_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_casestudy', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Integration', max_length=255)),
                ('subtitle', models.CharField(default='We collaborate with Top E-Commerce CMS in the World', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('shown', models.BooleanField(default=True)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study', to='bulqsoftDjango.casestudy')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_images', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
