# Generated by Django 3.1.14 on 2025-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulqsoftDjango', '0012_casestudy_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='image_height',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='study',
            name='image_width',
            field=models.IntegerField(default=720),
        ),
        migrations.AddField(
            model_name='study',
            name='link',
            field=models.CharField(default='#', max_length=2550),
        ),
    ]
