# Generated by Django 3.1.14 on 2025-04-13 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('bulqsoftDjango', '0013_auto_20250413_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_integration', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='Integration', max_length=255)),
                ('subtitle', models.CharField(default='We collaborate with Top E-Commerce CMS in the World', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('image_height', models.IntegerField(default=1000)),
                ('image_width', models.IntegerField(default=720)),
                ('shown', models.BooleanField(default=True)),
                ('link', models.CharField(default='#', max_length=2550)),
                ('Integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='bulqsoftDjango.integration')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integration_images', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='study',
            name='case_study',
        ),
        migrations.RemoveField(
            model_name='study',
            name='image',
        ),
        migrations.DeleteModel(
            name='CaseStudy',
        ),
        migrations.DeleteModel(
            name='Study',
        ),
    ]
