# Generated by Django 3.1.14 on 2025-04-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('bulqsoftDjango', '0014_auto_20250413_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepContainer',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='bulqsoftdjango_stepcontainer', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(max_length=2550)),
                ('shown', models.BooleanField(default=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='bulqsoftDjango.stepcontainer')),
            ],
        ),
    ]
